config/routes.rb
Rails.application.routes.draw do
  resources :themes
  root to: 'pages#home'

  devise_for :users



  resources :profiles, only: [:new, :edit, :create, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_and_belongs_to_many :themes
  belongs_to :user

validates :address, presence: true
validates :home_type, presence: true
validates :room_type, presence: true
validates :accommodate, presence: true
validates :bedroom_count, presence: true
validates :bathroom_count, presence: true
validates :listing_name, presence: true, length: { maximum: 50 }
validates :description, presence: true, length: { maximum: 500 }
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_and_belongs_to_many :rooms
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rooms, dependent: :destroy

  has_one :profile

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def show
  @themes = @room.themes
end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      redirect_to @room, notice: "Room created"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: "Room updated"
    else
      render :edit
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params
      .require(:room)
      .permit(
        :home_type, :room_type, :accommodate, :bedroom_count, :bathroom_count, :listing_name,
        :description, :address, :has_tv, :has_kitchen, :has_airco, :has_heating, :has_internet,
        :price, :active, theme_ids: [])
      
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>


  </head>

  <body>
    <%= render "shared/navbar" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>


</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
  <div class="form-group">
    <label>Home Type</label>
    <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]], id: "home_type", prompt: "Select home type", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Room Type</label>
    <%= f.select :room_type, [["Entire","Entire"], ["Private", "Private"], ["Shared", "Shared"]], prompt: "Select room type", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Number of People</label>
    <%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6+", 6]], prompt: "Select number of people", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bedrooms</label>
    <%= f.select :bedroom_count, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: "Select number of bedrooms", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bathrooms</label>
    <%= f.select :bathroom_count, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: "Select number of bathrooms", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Listing name</label>
    <%= f.text_field :listing_name, placeholder: "Listing name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, rows: 5, placeholder: "Say something about your place", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Address</label>
    <%= f.text_field :address, placeholder: "Address", class: "form-control" %>
  </div>

  <label>Amenities</label>

  <div class="form-group">
    <%= f.check_box :has_tv %> TV
  </div>
  <div class="form-group">
    <%= f.check_box :has_kitchen %> Kitchen
  </div>
  <div class="form-group">
    <%= f.check_box :has_internet %> Internet
  </div>

  <div class="form-group">
    <%= f.check_box :has_heating %> Heating
  </div>
  <div class="form-group">
    <%= f.check_box :has_airco %> Air Conditioning
  </div>

  <div class="form-group">
    <label>Nightly Price</label>
    <div class="input-group">
      <div class="input-group-addon">€</div>
      <%= f.number_field :price, placeholder: "eg. 100", class: "form-control" %>
    </div>
  </div>

  <label>Themes</label>

<%= f.collection_check_boxes(:theme_ids, Theme.all, :id, :name) do |b| %>
  <div class="form-group">
    <%= b.check_box(class: "check_box") %> <%= b.object.name %>
  </div>
<% end %>

  <label>Publish this place?</label>

  <div class="form-group">
    <%= f.check_box :active %> Active
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", rooms_path, class: "sidebar-link" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">

        <% @rooms.each do |room| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= room.listing_name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", room, class: "btn btn-default" %>
            <%= link_to "Update", edit_room_path(room), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new place", new_room_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new place
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading"><%= @room.listing_name %></div>

  <div class="panel-body">

    <p>Address: <%= @room.address %></p>
    <p>Host: <%= @room.user.email %></p>

    <!-- Main Info -->
    <h4>Main Info</h4>
    <p>Home Type: <%= @room.home_type %></p>
    <p><%= @room.accommodate %> <%= @room.accommodate > 1 ? "Guests" : "Guest" %></p>
    <p><%= @room.bedroom_count %> <%= @room.bedroom_count > 1 ? "Bedrooms" : "Bedroom" %></p>
    <p><%= @room.bathroom_count %> <%= @room.bathroom_count > 1 ? "Bathrooms" : "Bathroom" %></p>

    <!-- About -->
    <h4>About</h4>
    <p><%= @room.description %></p>

    <!-- Amenities -->
    <h4>Amenities</h4>
    <ul class="amenities">
      <li><%= !@room.has_tv ? ("<s>TV</s>").html_safe : "TV" %></li>
      <li><%= !@room.has_kitchen ? ("<del>Kitchen</del>").html_safe : "Kitchen" %></li>
      <li><%= !@room.has_internet ? ("<del>Internet</del>").html_safe : "Internet" %></li>
      <li><%= !@room.has_heating ? ("<del>Heating</del>").html_safe : "Heating" %></li>
      <li><%= !@room.has_airco ? ("<del>Air Conditioning</del>").html_safe : "Air Conditioning" %></li>
    </ul>


    <!-- Themes -->
    <h4>Themes</h4>
    <% @themes.each do |theme| %>
      <span class="label label-success"><%= theme.name %></span>
    <% end %>

  </div>

</div>

<%= link_to "Back", rooms_path, class: "btn btn-default" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurbnb", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
               <li><%= link_to "Your Listings", root_path %></li>
               <li role="separator" class="divider"></li>

               <% if current_user.has_profile? %>
                 <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
               <% else %>
                 <li><%= link_to "Create Profile", new_profile_path %></li>
               <% end %>
               <li><%= link_to "Edit Password", edit_user_registration_path %></li>

               <li role="separator" class="divider"></li>
               <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
             </ul>

           </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>